# Maintain data type for xml and calculations

target_pos: "2.85 0.0 0.8"
shelf_pos: "3.0 0.0 0.35"
moving_obs_pos: [8.0, 5.0, 0.1]

moving_obs_cmd: [0.0, 0.0, 0.0]

# CBF-CLF inequality parameters
alpha_static: 1.0
alpha_moving: 0.2
gamma: 0.2

# QP weight
x_weight: 1.0
y_weight: 1.0
theta_weight: 0.1
slack_static_weight: 1000.0
slack_moving_weight: 1000.0
slack_workspace_weight: 200.0

# save_path
pos_path: "./data/separated_pos_3"
cmd_path: "./data/separated_cmds_3"