# Maintain data type for xml and calculations

# Recording time
max_time: 10000

# Position
robot_pos: [0.0, 0.0, 0.793]
robot_orient: [0.707, 0.0, 0.0, 0.707]
robot_cmd: [0.0, -1.0, 0.0]
target_pos: "2.75 0.0 0.8"
shelf_pos: "3.0 0.0 0.35"
moving_obs_pos: [8.0, 5.0, 0.1]
moving_obs_cmd: [0.0, 0.0, 0.0]

# Sigmoid goal term parameters
sigmoid_a: 0.2
sigmoid_b: 2.0
sigmoid_c: 0.5

# CBF inequality parameters
alpha_static: 0.2
alpha_moving: 0.1

# QP weight
x_weight: 100.0
y_weight: 1.0
theta_weight: 0.01
slack_static_weight: 1000000.0
slack_moving_weight: 1000000.0

# save_path
pos_path: "./data/composite_CBF/composite_pos_lateral"
cmd_path: "./data/composite_CBF/composite_cmds_lateral"
val_path: "./data/composite_CBF/composite_vals_lateral"
col_path: "./data/composite_CBF/composite_col_lateral"